name: DevSecOps Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  sast:
    name: SAST - SonarQube
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build-and-scan:
    name: Build and Security Scan
    runs-on: self-hosted
    needs: sast
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build Docker image
        run: |
          docker build -t devsecops-lab:${{ github.sha }} .
          docker tag devsecops-lab:${{ github.sha }} devsecops-lab:latest

      - name: Trivy - Scan image for CVEs
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.cache/trivy:/root/.cache/trivy \
            -v ${{ github.workspace }}:/workspace \
            aquasec/trivy:latest image \
            --exit-code 0 \
            --severity HIGH,CRITICAL \
            --format sarif \
            --output /workspace/trivy-image.sarif \
            devsecops-lab:${{ github.sha }}

      - name: Trivy - Scan repo files
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v $HOME/.cache/trivy:/root/.cache/trivy \
            aquasec/trivy:latest fs \
            --exit-code 0 \
            --severity HIGH,CRITICAL \
            --format sarif \
            --output /workspace/trivy-fs.sarif \
            /workspace

      - name: Upload Trivy image results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98
        if: always()
        with:
          sarif_file: trivy-image.sarif
          category: trivy-image

      - name: Upload Trivy fs results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98
        if: always()
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs
